[package]
name = "termielle-emit"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
serde_json.workspace = true
termielle-core = { path = "../termielle-core" }
termielle-ipc = { path = "../termielle-ipc" }
thiserror.workspace = true

[dev-dependencies]
toml.workspace = true
